Hw 2 count det
devyueightfive/made-cpp-2020-hw pull request #2
Opened 2020-09-29 18:36 UTC by devyueightfive

count del ARM assembler solution

2020-10-01 12:51 UTC, xterrafunny requested changes

2020-10-01 12:51 UTC, xterrafunny commented on count_det/src/main.s
> +  // r0 for reading
Необходимо положить на стек значения регистров `r4-...`, значения которых изменяются во время работы функции, так как они могли хранить данные вне функции

2020-10-01 12:51 UTC, xterrafunny commented on count_det/src/main.s
> +
А здесь необходимо сделать `pop` со стека

2020-10-06 18:32 UTC, devyueightfive commented on count_det/src/main.s
> +  // r0 for reading
Добавил регистры r4-r7 в стек.

2020-10-06 18:33 UTC, devyueightfive commented
push и pop добавлены для используемых регистров r4-r7

2020-10-08 18:08 UTC, merged