Proj 1 vector operations
devyueightfive/made-cpp-2020-hw pull request #4
Opened 2020-10-06 17:25 UTC by devyueightfive

hw_project_1_vector_operations

2020-10-07 11:28 UTC, devyueightfive commented
Функции сонаправленности объединил в одну is_collinear

2020-10-15 21:16 UTC, SweetWeakness requested changes

2020-10-15 21:16 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    return std::vector<double>(a);// copy of a
2 пробела надо (табуляция, кодстайл)

2020-10-15 21:16 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    a.clear();// clear input container
сюда бы resize()

2020-10-15 21:16 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +        a.push_back(value);// fill container
чтобы не было этого

2020-10-15 21:16 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    }
через for и std::swap

2020-10-15 21:16 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +    return true;
можно проще
находим коэффициент в самом начале (если это возможно конечно же)
дальше проверяем оставшиеся элементы (модуль разности больше эпсилона)

2020-10-15 21:16 UTC, SweetWeakness commented on vector_operations/src/vector_ops.h
> +}
через коллиниарность

2020-10-20 20:35 UTC, devyueightfive commented on vector_operations/src/vector_ops.h
> +    return std::vector<double>(a);// copy of a
поправил табулицию = 4 пробела в кодстайле

2020-10-20 20:36 UTC, devyueightfive commented on vector_operations/src/vector_ops.h
> +    a.clear();// clear input container
resize добавил

2020-10-20 20:38 UTC, devyueightfive commented
Табуляция поправлена = 4 пробела.
resize добавил
обмен значениями между переменными через std::swap
Поправлены функции коллинеарности и соноправленности

2020-10-30 18:51 UTC, merged