Hw 5 chuck allocator
devyueightfive/made-cpp-2020-hw pull request #6
Opened 2020-10-27 20:15 UTC by devyueightfive

Домашняя работа номер 5

2020-10-31 13:47 UTC, SweetWeakness requested changes
PS: Это Константин, добавьте меня контрибом в репу! Скиньте инвайт в телеграм

2020-10-31 13:47 UTC, SweetWeakness commented on chuck_allocator/chunk_allocator.h
> +        Chunk *prev;
Нет, на предыдущие указатель не надо соxранять. Нужно на следующий, иначе работать верно не будет. Подумайте о том что будет происxодить при аллокации нового чанка ПОСЛЕ ситуации a = b

2020-10-31 13:47 UTC, SweetWeakness commented on chuck_allocator/chunk_allocator.h
> +            std::cout << (alloc ? "Alloc: " : "Dealloc: ") << sizeof(T) * n
#define DEBUG ?

2020-10-31 13:47 UTC, SweetWeakness commented on chuck_allocator/chunk_allocator.h
> +        static uint copies;
Нет, это не правильно. Никакиx static-полей быть не должно. Подумайте почему

2020-10-31 13:47 UTC, SweetWeakness commented on chuck_allocator/chunk_allocator.h
> +        T *allocate(size_t n);
У вас же есть pointer, size_type. Зачем вам T*, size_t ???

2020-11-05 07:53 UTC, devyueightfive commented
1. Перестроил структуру по парадигме Allocator->List->Node->Chunk
2. List хранит только начало
3. Счетчик строится на куче. В конструкторе копирования присваиваются ссылки на List и счетчик (+увеличивается). В операторе копирования проверяется предыдущий счетчик. В случае единственности ссылки аллокатора на List, вызывается деструкторы List и счетчика. 
4. Используется DEBUG для отладочных записей
5. от T, T*, size_t перешел к value_type, pointer, size_type

2020-11-05 21:24 UTC, merged